### ISSUE TITLE
Does it run on Visual studio 2015?

### ISSUE THREAD

**Issue by KhoaM** [limingjie/pdf_to_image#4]
When i convert the project from 2013 to 2015 and i run it it says something like: "..\mupdf\lib\release_x64\was been created with an older compliator than the other object"

**Comment by limingjie** [comment]
Hi KhoaM,

Sorry for late reply.

The prebuilt libraries are VS2013 only. To build on VS2015, instead of using prebuilts, you need first follow the manual build steps to build FLTK and MuPDF, then build PDF to image.

Thanks,
Mingjie
