### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by RichardB01** [limingjie/pdf_to_image#5]
Hi, great program. Looking to use it via the command line such as:
`pdf_to_image.exe "input.pdf" "output.png"`
Thanks.

**Comment by esidegallery** [comment]
I agree, this would be very useful

**Comment by limingjie** [comment]
ImageMagick convert is probably the best way to go. I write this program mainly to help people without much technical background. :)
https://imagemagick.org/script/convert.php
