### ISSUE TITLE
Which open source/free software license does this software follow?

### ISSUE THREAD

**Issue by ZhouJiatai** [limingjie/pdf_to_image#6]
This is such a nice software, but I can't find any open source/free software licenses under the source code folder. Which license does this software follow? Or it doesn't follow open source/free software licenses? Is it "all rights reserved"?

**Comment by limingjie** [comment]
@ZhouJiatai You can assume there is not any restriction to reuse my code, but you may have to follow the licenses of MuPDF and FLTK.
